spring:
  application:
    name: rtccts
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        key.deserializer: org.apache.kafka.common.serialization.AvroDeserializer
        value.deserializer: org.apache.kafka.common.serialization.AvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: username
    password: password
    driver-class-name:
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        kafka: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# Kafka topics configuration
kafka:
  topics:
    main-topic: main-topic
    dlq-topic: dlq-topic

